language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

#before_install:
#  - sudo apt-get update
#  - sudo apt-get install -y python-logilab-common

install:
  - pip install future
  - pip install mock
  - python setup.py install

script: pytest